### PR TITLE
add support to flink 1.14

### PR DESCRIPTION
**Pull request by JimWen**
with compatible support to filnk before 1.14 .
if you want to use flink before 1.14 , use maven with profile flink-before-1.14.

### CODE REVIEW

**Comment by Nicole00** [comment]
If we just change the flink's version, then nebula-flink-connector snapshot will just support flink 1.14 but not 1.11.

**Comment by JimWen** [comment]
> If we just change the flink's version, then can nebula-flink-connector snapshot support flink 1.11 ?

If you want to run the Table API & SQL programs locally within your IDE,  you should  use maven with profile flink-before-1.14 which will include module flink-table-planner-blink . 

Other way, just change the flink's version is enough.

**Comment by Nicole00** [comment]
> > If we just change the flink's version, then can nebula-flink-connector snapshot support flink 1.11 ?
> 
> Before flink 1.14, if you want to run the Table API & SQL programs locally within your IDE, you should use maven with profile flink-before-1.14 which will include module flink-table-planner-blink .
> 
> Other way, just change the flink's version is enough.

For snapshot version, it still just supports flink1.11. This pr is very useful for users who want to compile and package it from source code.
Or maybe we can add some workflow to compile two nebula-flink-connector with different flink version. refer exchange which is compatible with different spark and scala.

**Comment by JimWen** [comment]
> > > If we just change the flink's version, then can nebula-flink-connector snapshot support flink 1.11 ?
> > 
> > 
> > Before flink 1.14, if you want to run the Table API & SQL programs locally within your IDE, you should use maven with profile flink-before-1.14 which will include module flink-table-planner-blink .
> > Other way, just change the flink's version is enough.
> 
> For snapshot version, it still just supports flink1.11. This pr is very useful for users who want to compile and package it from source code. Or maybe we can add some workflow to compile two nebula-flink-connector with different flink version. refer exchange which is compatible with different spark and scala.

Providing different versions of compiled products is a common practice in the flink community. Different flink version may have interface and implementation changes, and compatibility is not guaranteed.

**Comment by Nicole00** [comment]
> > > > If we just change the flink's version, then can nebula-flink-connector snapshot support flink 1.11 ?
> > > 
> > > 
> > > Before flink 1.14, if you want to run the Table API & SQL programs locally within your IDE, you should use maven with profile flink-before-1.14 which will include module flink-table-planner-blink .
> > > Other way, just change the flink's version is enough.
> > 
> > 
> > For snapshot version, it still just supports flink1.11. This pr is very useful for users who want to compile and package it from source code. Or maybe we can add some workflow to compile two nebula-flink-connector with different flink version. refer exchange which is compatible with different spark and scala.
> 
> Providing different versions of compiled products is a common practice in the flink community. Different flink version may have interface and implementation changes, and compatibility is not guaranteed.

Yeah, different flink versions have incompatible interfaces, that's why we need to provide another directory to support other flink version at the code level. 
And for flink connector, if we support different flink versions, maybe we should give an available dependency in maven for both flink 1.14 and other version, not just a compile product.

**Pull request closed without merging**
