### PR TITLE
Add vertex delete with edge

### PR DESCRIPTION
**Pull request by StrangerOfDawah**
## What type of PR is this?
- [ ] bug
- [x] feature
- [ ] enhancement

## Description
This patch adds support for deleting vertices along with their edges in the Nebula connector. A new feature flag, `isDeleteExecutedWithEdges`, is introduced to control this behavior. Additionally, tests are added to verify the new functionality while ensuring existing functionality remains unaffected.

## How do you solve it?
1. **NebulaVertices Class:**
   - Added a new boolean field `isDeleteExecutedWithEdges`.
   - Modified the constructor to initialize this field.
   - Updated the `getDeleteStatement` method to use the appropriate delete template based on the `isDeleteExecutedWithEdges` flag.

2. **VertexExecutionOptions Class:**
   - Added the `isDeleteExecutedWithEdges` field.
   - Updated the constructor and builder pattern to include this new field.
   - Added a getter method for `isDeleteExecutedWithEdges`.

3. **NebulaVertexBatchExecutor Class:**
   - Passed the `isDeleteExecutedWithEdges` flag from `VertexExecutionOptions` to `NebulaVertices`.

4. **NebulaConstant Class:**
   - Added a new delete template `DELETE_VERTEX_TEMPLATE_WITH_EDGE`.

5. **NebulaVerticesTest Class:**
   - Added new test methods `testGetDeleteStatementWithEdges` and `testGetDeleteStatementWithPolicyAndEdges` to validate the new delete behavior.

## Special notes for your reviewer
- **Impact:** This patch maintains backward compatibility by preserving the existing delete functionality. The new feature is controlled by the `isDeleteExecutedWithEdges` flag, ensuring that existing code paths remain unchanged unless explicitly modified to use the new feature.
- **Design Document:** The design follows the existing pattern of handling execution options and statements in the Nebula connector. The addition of a feature flag allows for flexible extension of delete behavior without intrusive changes.
- **Testing:** Comprehensive tests have been added to verify both the new and existing functionalities.

### CODE REVIEW

**Review by wey-gu — APPROVED** [review]
Thanks!🫡

**Comment by StrangerOfDawah** [comment]
@Nicole00 how is everything going?

**Review by Nicole00 — APPROVED** [review]
LGTM, excellent job!

**Comment by nick13145** [comment]
@Nicole00 could you publish new version of that library?
https://central.sonatype.com/artifact/com.vesoft/nebula-flink-connector/versions
At the moment there are no any new versions since 26 April. 

Thanks in advance

**Comment by StrangerOfDawah** [comment]
@wey-gu @Nicole00  Hi!

Can you please increment the version so that the new version is recorded in the public artifacts?

**Comment by wey-gu** [comment]
@Nicole00 could we create a minor version release?

**Comment by Nicole00** [comment]
> @Nicole00 could we create a minor version release?

Yeah, we can publish a minor version.

**Comment by Nicole00** [comment]
@nick13145 @StrangerOfDawah @wey-gu version 3.8.1 already released to https://repo1.maven.org/maven2/com/vesoft/nebula-flink-connector/

**Pull request merged**
